# Add a comment to github PRs marked with the "reviewer needed" label
name: "Add comment to PRs marked 'reviewer needed'"
on:
  pull_request_target:
      types: [labeled]
jobs:
  add_comment:
    if: github.repository == 'Klipper3d/klipper'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            if (context.payload.label.name != "reviewer needed")
              return;
            if (context.payload.pull_request.assignees.length > 0)
              return;
            msg = "Thank you for your contribution to Klipper."
                + " Unfortunately, a reviewer has not assigned themselves to"
                + " this GitHub Pull Request."
                + " Further information is available at:"
                + " https://www.klipper3d.org/CONTRIBUTING.html"
                + "\n\n"
                + "Be sure to discuss any enhancements or changes in behavior"
                + " on the [Klipper Discourse]"
                + "(https://www.klipper3d.org/Contact.html#community-forum)"
                + " server. Reviewers can reach out on that forum to let you"
                + " know if they are interested and when they are available."
                + "\n\n"
                + "Unfortunately, if a reviewer does not assign themselves to"
                + " this GitHub Pull Request then it will be automatically"
                + " closed."
                + "\n\n"
                + "Best regards,\n"
                + "~ Your friendly GitIssueBot"
                + "\n\n"
                + "PS: I'm just an automated script, not a human being.";
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: msg
            })
